plugins:
  group_discourse_enabled:
    default: true
    client: true
  group_menu:
    client: true
    refresh: true
    type: list
    default: "latest|new|unread|top"
    regex: "latest"
    regex_error: "site_settings.errors.must_include_latest"
    choices:
     - latest
     - new
     - unread
     - top